on: push
name: Valist Publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: valist-io/valist-github-action@v2.2.0
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          account: newway
          project: xcrosslend
          release: 1
          files: '**'
